all: test test test test test

test: insert bucket counting heap merge quick_f quick bubble

bubble: bubble_a bubble_b bubble_c bubble_d

bubble_a:
	time ruby bubble.rb < 25000a.in
	time ruby bubble.rb < 50000a.in
	time ruby bubble.rb < 100000a.in
	time ruby bubble.rb < 1000000a.in

bubble_b:
	time ruby bubble.rb < 25000b.in
	time ruby bubble.rb < 50000b.in
	time ruby bubble.rb < 100000b.in
	time ruby bubble.rb < 1000000b.in

bubble_c:
	time ruby bubble.rb < 25000c.in
	time ruby bubble.rb < 50000c.in
	time ruby bubble.rb < 100000c.in
	time ruby bubble.rb < 1000000c.in

bubble_d:
	time ruby bubble.rb < 25000d.in
	time ruby bubble.rb < 50000d.in
	time ruby bubble.rb < 100000d.in
	time ruby bubble.rb < 1000000d.in

bucket: bucket_a bucket_b bucket_c bucket_d

bucket_a:
	time ruby bucket.rb < 25000a.in
	time ruby bucket.rb < 50000a.in
	time ruby bucket.rb < 100000a.in
	time ruby bucket.rb < 1000000a.in

bucket_b:
	time ruby bucket.rb < 25000b.in
	time ruby bucket.rb < 50000b.in
	time ruby bucket.rb < 100000b.in
	time ruby bucket.rb < 1000000b.in

bucket_c:
	time ruby bucket.rb < 25000c.in
	time ruby bucket.rb < 50000c.in
	time ruby bucket.rb < 100000c.in
	time ruby bucket.rb < 1000000c.in

bucket_d:
	time ruby bucket.rb < 25000d.in
	time ruby bucket.rb < 50000d.in
	time ruby bucket.rb < 100000d.in
	time ruby bucket.rb < 1000000d.in

counting: counting_a counting_b counting_c counting_d

counting_a:
	time ruby counting.rb < 25000a.in
	time ruby counting.rb < 50000a.in
	time ruby counting.rb < 100000a.in
	time ruby counting.rb < 1000000a.in

counting_b:
	time ruby counting.rb < 25000b.in
	time ruby counting.rb < 50000b.in
	time ruby counting.rb < 100000b.in
	time ruby counting.rb < 1000000b.in

counting_c:
	time ruby counting.rb < 25000c.in
	time ruby counting.rb < 50000c.in
	time ruby counting.rb < 100000c.in
	time ruby counting.rb < 1000000c.in

counting_d:
	time ruby counting.rb < 25000d.in
	time ruby counting.rb < 50000d.in
	time ruby counting.rb < 100000d.in
	time ruby counting.rb < 1000000d.in

heap: heap_a heap_b heap_c heap_d

heap_a:
	time ruby heap.rb < 25000a.in
	time ruby heap.rb < 50000a.in
	time ruby heap.rb < 100000a.in
	time ruby heap.rb < 1000000a.in

heap_b:
	time ruby heap.rb < 25000b.in
	time ruby heap.rb < 50000b.in
	time ruby heap.rb < 100000b.in
	time ruby heap.rb < 1000000b.in

heap_c:
	time ruby heap.rb < 25000c.in
	time ruby heap.rb < 50000c.in
	time ruby heap.rb < 100000c.in
	time ruby heap.rb < 1000000c.in

heap_d:
	time ruby heap.rb < 25000d.in
	time ruby heap.rb < 50000d.in
	time ruby heap.rb < 100000d.in
	time ruby heap.rb < 1000000d.in

merge: merge_a merge_b merge_c merge_d

merge_a:
	time ruby merge.rb < 25000a.in
	time ruby merge.rb < 50000a.in
	time ruby merge.rb < 100000a.in
	time ruby merge.rb < 1000000a.in

merge_b:
	time ruby merge.rb < 25000b.in
	time ruby merge.rb < 50000b.in
	time ruby merge.rb < 100000b.in
	time ruby merge.rb < 1000000b.in

merge_c:
	time ruby merge.rb < 25000c.in
	time ruby merge.rb < 50000c.in
	time ruby merge.rb < 100000c.in
	time ruby merge.rb < 1000000c.in

merge_d:
	time ruby merge.rb < 25000d.in
	time ruby merge.rb < 50000d.in
	time ruby merge.rb < 100000d.in
	time ruby merge.rb < 1000000d.in

quick_f: quick_fa quick_fb quick_fc quick_fd

quick_fa:
	time ruby quick_first.rb < 25000a.in
	time ruby quick_first.rb < 50000a.in
	time ruby quick_first.rb < 100000a.in
	time ruby quick_first.rb < 1000000a.in

quick_fb:
	time ruby quick_first.rb < 25000b.in
	time ruby quick_first.rb < 50000b.in
	time ruby quick_first.rb < 100000b.in
	time ruby quick_first.rb < 1000000b.in

quick_fc:
	time ruby quick_first.rb < 25000c.in
	time ruby quick_first.rb < 50000c.in
	time ruby quick_first.rb < 100000c.in
	time ruby quick_first.rb < 1000000c.in

quick_fd:
	time ruby quick_first.rb < 25000d.in
	time ruby quick_first.rb < 50000d.in
	time ruby quick_first.rb < 100000d.in
	time ruby quick_first.rb < 1000000d.in

quick: quick_a quick_b quick_c quick_d

quick_a:
	time ruby quick.rb < 25000a.in
	time ruby quick.rb < 50000a.in
	time ruby quick.rb < 100000a.in
	time ruby quick.rb < 1000000a.in

quick_b:
	time ruby quick.rb < 25000b.in
	time ruby quick.rb < 50000b.in
	time ruby quick.rb < 100000b.in
	time ruby quick.rb < 1000000b.in

quick_c:
	time ruby quick.rb < 25000c.in
	time ruby quick.rb < 50000c.in
	time ruby quick.rb < 100000c.in
	time ruby quick.rb < 1000000c.in

quick_d:
	time ruby quick.rb < 25000d.in
	time ruby quick.rb < 50000d.in
	time ruby quick.rb < 100000d.in
	time ruby quick.rb < 1000000d.in

insert: insert_a insert_b insert_c insert_d

insert_a:
	time ruby insert.rb < 25000a.in
	time ruby insert.rb < 50000a.in
	time ruby insert.rb < 100000a.in
	time ruby insert.rb < 1000000a.in

insert_b:
	time ruby insert.rb < 25000b.in
	time ruby insert.rb < 50000b.in
	time ruby insert.rb < 100000b.in
	time ruby insert.rb < 1000000b.in

insert_c:
	time ruby insert.rb < 25000c.in
	time ruby insert.rb < 50000c.in
	time ruby insert.rb < 100000c.in
	time ruby insert.rb < 1000000c.in

insert_d:
	time ruby insert.rb < 25000d.in
	time ruby insert.rb < 50000d.in
	time ruby insert.rb < 100000d.in
	time ruby insert.rb < 1000000d.in
